server:
  ssl:
    key-alias: instagram-oauth
    key-store: classpath:instagram-oauth.jks
    key-store-type: JKS
    key-store-password: password

  port: 8085

spring:
  application:
    name: OAUTH-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address:true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      authorize-retry:
        max-attempts: 3
        wait-duration: 5s
      get-access-token-retry:
        max-attempts: 3
        wait-duration: 5s